//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public int IdType { get; set; }
        public int IdAuthor { get; set; }
        public int IdStatus { get; set; }
        public string Publisher { get; set; }
        public int Price { get; set; }
        public int Amount { get; set; }
        public int Status { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual BookStatu BookStatu { get; set; }
        public virtual BookType BookType { get; set; }
    }
}
