//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BorrowTickets = new HashSet<BorrowTicket>();
            this.BorrowBooks = new HashSet<BorrowBook>();
        }
    
        public int id { get; set; }
        public int IdType { get; set; }
        public int IdAuthor { get; set; }
        public string Publisher { get; set; }
        public int Price { get; set; }
        public int Amount { get; set; }
        public int Status { get; set; }
        public string Name { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual BookType BookType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowTicket> BorrowTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowBook> BorrowBooks { get; set; }
    }
}
